sudo: required

env:
  - CASES=_basic.sh
  - CASES=_kerberos.sh

before_script:
- USE_MINIKUBE_DRIVER_NONE=true USE_SUDO_MINIKUBE=true tests/setup.sh

script:
- tests/run.sh

after_script:
- tests/cleanup.sh
- tests/teardown.sh
