dependencies:
  - name: zookeeper
    version: "0.6.3"
    repository: "https://kubernetes-charts-incubator.storage.googleapis.com/"
    condition: global.namenodeHAEnabled
  - name: journalnode
    version: "0.1.0"
    repository: "file://../charts/hdfs-journalnode-k8s"
    condition: global.namenodeHAEnabled
