# Default values for template variables.

# Name of the k8s config map containing Hadoop config files such as core-site.xml
# and hdfs-site.xml.
hdfsConfigMap: hdfs-config

# Whether or not Kerberos support is enabled.
kerberosEnabled: false

# Effective only if Kerberos is enabled. Name of the k8s config map containing
# the kerberos config file.
kerberosConfigMap: kerberos-config

# Effective only if Kerberos is enabled. Name of the kerberos config file inside
# the config map.
kerberosConfigFileName: krb5.conf
