# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: krb5-server
  labels:
    app: krb5-server
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: kdc-tcp
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: kdc-udp
  clusterIP: None
  selector:
    app: {{ template "krb5-server.name" . }}
    release: {{ .Release.Name }}
