# Default values for krb5-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gcavalcante8808/krb5-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

